'use strict';

// tests for helloWorldOne
// Generated by serverless-jest-plugin

const config = require('../../jest-config.json');
const request = require('supertest')(config.testUrl);

describe('/user/helloWorldOne routes', () => {
    it('GET /user/helloWorldOne ', () => {
        return request
            .get('/user/helloWorldOne')
            .expect(200)
            .then((res) => {
                expect(res).toBeDefined();
            });
    });
});