'use strict';

// tests for helloWorldTwo
// Generated by serverless-jest-plugin

const config = require('../../jest-config.json');
const request = require('supertest')(config.testUrl);

describe('/user/helloWorldTwo routes', () => {
    it('GET /user/helloWorldTwo ', () => {
        return request
            .get('/user/helloWorldTwo')
            .expect(200)
            .then((res) => {
                expect(res).toBeDefined();
            });
    });
});