'use strict';

// tests for helloWorldThree
// Generated by serverless-jest-plugin

const config = require('../../jest-config.json');
const request = require('supertest')(config.testUrl);

describe('/user/helloWorldThree routes', () => {
    it('GET /user/helloWorldThree ', () => {
        return request
            .get('/user/helloWorldThree')
            .expect(200)
            .then((res) => {
                expect(res).toBeDefined();
            });
    });
});